"use client";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, Stars } from "@react-three/drei";
import { useRef, useState } from "react";
import * as THREE from "three";
import { usePredictionStore } from "@/store/usePredictionStore";
const colors = ["#22c55e", "#eab308", "#f97316", "#ef4444", "#a855f7"];
function Sun({ speed, corona }: { speed: number; corona: boolean }) { const mesh = useRef<THREE.Mesh>(null); const { prediction } = usePredictionStore(); useFrame(() => { if (mesh.current) mesh.current.rotation.y += .003 * speed; }); return <group><mesh ref={mesh}><sphereGeometry args={[1,64,64]}/><meshStandardMaterial color="#f97316" emissive={colors[prediction.predicted_class]} emissiveIntensity={.8} roughness={.8}/></mesh>{corona&&<mesh scale={1.14}><sphereGeometry args={[1,48,48]}/><meshBasicMaterial color={colors[prediction.predicted_class]} transparent opacity={.16} side={THREE.BackSide}/></mesh>}</group> }
function Regions({ visible, onSelect }: { visible: boolean; onSelect: (region: {id:string;lat:number;lon:number;class:number;confidence?:number;intensity?:number}) => void }) { const { prediction } = usePredictionStore(); if (!visible) return null; return <>{(prediction.active_regions ?? []).map((region,index) => { const lat=region.lat*Math.PI/180, lon=region.lon*Math.PI/180; const position:[number,number,number]=[1.08*Math.cos(lat)*Math.cos(lon),1.08*Math.sin(lat),1.08*Math.cos(lat)*Math.sin(lon)]; return <mesh key={region.id} position={position} onClick={(event)=>{event.stopPropagation();onSelect(region)}}><sphereGeometry args={[.05,16,16]}/><meshStandardMaterial color={colors[region.class]} emissive={colors[region.class]} emissiveIntensity={2}/></mesh>})}</> }
export default function SunScene({ mini = false }: { mini?: boolean }) { const [regions,setRegions]=useState(true),[corona,setCorona]=useState(true),[speed,setSpeed]=useState(1),[selected,setSelected]=useState<{id:string;lat:number;lon:number;class:number;confidence?:number;intensity?:number}|null>(null); return <div className={mini?"h-36":"relative h-[540px] overflow-hidden rounded-2xl border border-[#21262d] bg-black"}>{!mini&&<div className="absolute right-3 top-3 z-10 space-y-2 rounded bg-black/65 p-3 text-xs"><label className="block"><input checked={regions} onChange={e=>setRegions(e.target.checked)} type="checkbox"/> Active regions</label><label className="block"><input checked={corona} onChange={e=>setCorona(e.target.checked)} type="checkbox"/> Corona layer</label><label>Rotation <input aria-label="Rotation speed" type="range" min="0" max="3" step=".25" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label></div>}<Canvas camera={{position:[0,0,3],fov:45}}><ambientLight intensity={.2}/><pointLight position={[0,0,2]} intensity={25} color="#ff6a00"/><Stars radius={100} depth={50} count={mini?300:2500} factor={4}/><Sun speed={speed} corona={corona}/><Regions visible={regions} onSelect={setSelected}/><OrbitControls enableZoom={!mini} autoRotate={mini} autoRotateSpeed={.4}/></Canvas>{selected&&!mini&&<div className="absolute bottom-3 left-3 rounded-lg border border-orange-400/40 bg-[#0d1117e8] p-3 text-sm"><b>{selected.id}</b><br/>Lat {selected.lat}° · Lon {selected.lon}°<br/>Class {selected.class} · {(selected.confidence ?? 0)*100}%</div>}</div> }
